name: Telegram Bot Runner

on:
  push:
    branches: [ main ]
  schedule:
    # Запуск каждые 5 часов (чтобы не упираться в лимит 6 часов)
    - cron: '0 */5 * * *'
  workflow_dispatch: # Возможность запустить кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    # Запрещаем запуск нескольких копий бота одновременно
    concurrency: 
      group: telegram-bot
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pyTelegramBotAPI

      - name: Run Python Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        # Цикл while заставит скрипт перезапуститься, если он упадет с ошибкой
        run: |
          while true; do
            python bot.py
            echo "Скрипт упал, перезапуск через 5 секунд..."
            sleep 5
          done
